# Generated by Django 3.0.6 on 2020-05-14 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 11, 23, 35, 115756), verbose_name='Date Published'),
        ),
    ]
