# Generated by Django 3.0.6 on 2020-05-14 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200514_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 11, 47, 49, 870321), verbose_name='Date Published'),
        ),
    ]
