# Generated by Django 3.0.6 on 2020-05-15 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200514_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 30, 32, 320166), verbose_name='Date Published'),
        ),
    ]
