# Generated by Django 3.0.6 on 2020-05-17 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200517_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorials_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 12, 48, 11, 917702), verbose_name='Date Published'),
        ),
    ]
