# Generated by Django 3.0.6 on 2020-05-17 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200517_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 12, 48, 29, 171486), verbose_name='Date Published'),
        ),
    ]
