# Generated by Django 3.0.6 on 2020-05-17 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200517_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 12, 50, 44, 817517), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='tutorial_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
