# Generated by Django 3.0.6 on 2020-05-17 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200517_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 17, 12, 56, 270109), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='series',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
