# Generated by Django 3.0.6 on 2020-05-17 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200517_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialseries',
            name='id',
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='seriesid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 17, 18, 19, 565002), verbose_name='Date Published'),
        ),
    ]
