# Generated by Django 3.0.6 on 2020-05-18 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200518_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 11, 15, 6, 451438), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='seriesid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
