# Generated by Django 3.0.6 on 2020-05-19 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200518_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialseries',
            name='seriesid',
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 11, 25, 9, 833022), verbose_name='Date Published'),
        ),
    ]
