# Generated by Django 3.0.6 on 2020-05-19 06:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200519_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='category',
            new_name='tutorialcategory',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='series',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorialseries',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TutorialSeries', verbose_name='series'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 11, 48, 53, 877563), verbose_name='Date Published'),
        ),
    ]
